const request = require('supertest');
const app = require('../src/app');
const { storage } = require('../src/services/storageService');

beforeEach(() => {
  storage.clear();
});

afterAll(() => {
  storage.clear();
});

describe('Smart Expense Tracker API Integration Tests', () => {
  test('GET / - Health check', async () => {
    const response = await request(app).get('/');
    expect(response.status).toBe(200);
    expect(response.body.status).toBe('online');
    expect(response.body.docs).toBe('/docs');
  });

  test('POST /expenses - Add expense with custom ID', async () => {
    const payload = {
      id: 'exp-101',
      title: 'Groceries',
      amount: 45.50,
      category: 'Food',
      date: '2026-07-30',
    };

    const response = await request(app).post('/expenses').send(payload);
    expect(response.status).toBe(201);
    expect(response.body.id).toBe('exp-101');
    expect(response.body.title).toBe('Groceries');
    expect(response.body.amount).toBe(45.50);
    expect(response.body.category).toBe('Food');
    expect(response.body.date).toBe('2026-07-30');
  });

  test('POST /expenses - Add expense with autogenerated ID', async () => {
    const payload = {
      title: 'Bus Pass',
      amount: 15.00,
      category: 'Transport',
      date: '2026-07-31',
    };

    const response = await request(app).post('/expenses').send(payload);
    expect(response.status).toBe(201);
    expect(response.body).toHaveProperty('id');
    expect(typeof response.body.id).toBe('string');
    expect(response.body.title).toBe('Bus Pass');
  });

  test('POST /expenses - Reject duplicate ID', async () => {
    const payload = {
      id: 'dup-1',
      title: 'Coffee',
      amount: 4.50,
      category: 'Food',
      date: '2026-07-31',
    };

    await request(app).post('/expenses').send(payload);
    const response = await request(app).post('/expenses').send(payload);

    expect(response.status).toBe(400);
    expect(response.body.error).toMatch(/already exists/i);
  });

  test('POST /expenses - Reject negative or zero amount', async () => {
    const payload = {
      title: 'Invalid',
      amount: -10.00,
      category: 'Food',
      date: '2026-07-31',
    };

    const response = await request(app).post('/expenses').send(payload);
    expect(response.status).toBe(400);
  });

  test('POST /expenses - Reject empty title or whitespace', async () => {
    const payload = {
      title: '   ',
      amount: 10.00,
      category: 'Food',
      date: '2026-07-31',
    };

    const response = await request(app).post('/expenses').send(payload);
    expect(response.status).toBe(400);
  });

  test('POST /expenses - Reject invalid date', async () => {
    const payload = {
      title: 'Lunch',
      amount: 10.00,
      category: 'Food',
      date: 'invalid-date-string',
    };

    const response = await request(app).post('/expenses').send(payload);
    expect(response.status).toBe(400);
  });

  test('GET /expenses - Retrieve all expenses & filter by category', async () => {
    const expenses = [
      { id: '1', title: 'Lunch', amount: 12.50, category: 'Food', date: '2026-07-28' },
      { id: '2', title: 'Dinner', amount: 25.00, category: 'Food', date: '2026-07-29' },
      { id: '3', title: 'Taxi', amount: 18.00, category: 'Transport', date: '2026-07-30' },
    ];

    for (const exp of expenses) {
      await request(app).post('/expenses').send(exp);
    }

    // View all
    const allRes = await request(app).get('/expenses');
    expect(allRes.status).toBe(200);
    expect(allRes.body.length).toBe(3);

    // Filter Food via query parameter
    const foodRes = await request(app).get('/expenses?category=Food');
    expect(foodRes.status).toBe(200);
    expect(foodRes.body.length).toBe(2);
    expect(foodRes.body.every((i) => i.category === 'Food')).toBe(true);

    // Dedicated filter via GET /expenses/filter?category=Food
    const dedicatedQueryRes = await request(app).get('/expenses/filter?category=Food');
    expect(dedicatedQueryRes.status).toBe(200);
    expect(dedicatedQueryRes.body.length).toBe(2);

    // Filter case-insensitive
    const transportRes = await request(app).get('/expenses?category=transport');
    expect(transportRes.status).toBe(200);
    expect(transportRes.body.length).toBe(1);
    expect(transportRes.body[0].title).toBe('Taxi');
  });

  test('GET /expenses/totals - Calculate overall and category totals', async () => {
    const expenses = [
      { id: '1', title: 'Lunch', amount: 10.00, category: 'Food', date: '2026-07-28' },
      { id: '2', title: 'Snack', amount: 5.50, category: 'Food', date: '2026-07-29' },
      { id: '3', title: 'Metro', amount: 4.50, category: 'Transport', date: '2026-07-30' },
      { id: '4', title: 'Book', amount: 20.00, category: 'Education', date: '2026-07-31' },
    ];

    for (const exp of expenses) {
      await request(app).post('/expenses').send(exp);
    }

    const response = await request(app).get('/expenses/totals');
    expect(response.status).toBe(200);
    expect(response.body.total_amount).toBe(40.00);
    expect(response.body.by_category).toEqual({
      Food: 15.50,
      Transport: 4.50,
      Education: 20.00,
    });
  });

  test('DELETE /expenses/:id - Delete existing expense', async () => {
    const payload = {
      id: 'del-101',
      title: 'Movie',
      amount: 15.00,
      category: 'Entertainment',
      date: '2026-07-31',
    };

    await request(app).post('/expenses').send(payload);

    const deleteRes = await request(app).delete('/expenses/del-101');
    expect(deleteRes.status).toBe(200);
    expect(deleteRes.body.message).toMatch(/successfully deleted/i);

    const checkRes = await request(app).get('/expenses');
    expect(checkRes.body.length).toBe(0);
  });

  test('DELETE /expenses/:id - 404 for non-existent expense', async () => {
    const response = await request(app).delete('/expenses/non-existent-id');
    expect(response.status).toBe(404);
    expect(response.body.error).toMatch(/not found/i);
  });
});
